name: neotradingbotfront1777
description: "Dashboard di controllo per il bot di trading di criptovalute neotradingbot1777."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^8.0.0

  #-- Core & Architettura --
  equatable: ^2.0.5
  fpdart: ^1.1.0

  #-- State Management --
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  #-- gRPC & Network --
  grpc: ^5.1.0
  protobuf: ^6.0.0
  auto_size_text: ^3.0.0
  fixnum: ^1.1.1

  #-- Charts & Visualization --
  fl_chart: ^1.0.0

  #-- UI & UX --
  flutter_animate: ^4.5.0
  logger: ^2.6.1
  shared_preferences: ^2.5.0
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  mockito: ^5.5.0

  build_runner: ^2.4.0
  protoc_plugin: ^25.0.0
  test: ^1.25.15
  integration_test:
    sdk: flutter
  mutation_test: ^1.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design:
    true

    # Prevediamo giÃ  le sezioni per assets futuri
  assets:
    - assets/certs/
  # fonts:
  #   - family: SoloLevelingFont
  #     fonts:
  #       - asset: assets/fonts/SoloLeveling.ttf
